### ISSUE TITLE
ToString() format is not correct

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/NumSharp#187]
`np.array(new int[][] { new int[] { 12 } });` the string format should be `[[ 12 ]]`

![image](https://user-images.githubusercontent.com/33488376/50741716-b63a9480-11c6-11e9-9cf9-3e3375345cbe.png)

**Comment by dotChris90** [comment]
damn totally forgot to adapt it.

I will check it tomorrow. maybe move this method to castings.... since it is converting

**Comment by dotChris90** [comment]
@Esther2013 @Oceania2018 can somebody of you check the view in Visual Studio? In Code it looks more or less ok - do not use VS. ;) 

It was my bad seems xD I dont know when but the for loop was terminated at 2nd element because it did not check the size .... it checked the ndim. NDIM for matrix is always 2 .... -.-

**Comment by Esther2013** [comment]
@dotChris90 It works, thank you for your quick fix.
![image](https://user-images.githubusercontent.com/33488376/50789766-bf893700-1282-11e9-8353-e19ae08a8560.png)
