### ISSUE TITLE
Bitmap to NDArray

### ISSUE THREAD

**Issue by ggriffon** [SciSharp/NumSharp#289]
Hi, 
I have an issue while creating an NDArray from a Bitmap/Image, an exception is thrown.

```
var ndarray = np.array(img);
```

Exception message : Allocate Image
Stack Trace : 
   at NumSharp.Backends.TypedArrayStorage.Allocate(Shape shape, Type dtype)
   at NumSharp.np.array[T](T[] data)

**Comment by HJB83** [comment]
??? is it solved???

**Comment by Nucs** [comment]
NumSharp does not support `Image` directly.
Youll have to tranform the bitmap into a byte array and then feed it to `np.array`, see:
https://stackoverflow.com/questions/4747428/getting-rgb-array-from-image-in-c-sharp

**Comment by mjbedford2017** [comment]
@Nucs I see your post, thank you. However, when I try to convert the Bitmap to a byte array and feed it into an np.array, I get a 1D array and this exception when I try to run it through Tensorflow:

> System.Exception: 'input must be 4-dimensional[1] [[{{node Preprocessor/map/while/ResizeImage/ResizeBilinear}}]]' 

Here is the basic code I am using for now as a test:

```
      public void Score()
        {
            var modelPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, tensorPb);
            var testImage = new Bitmap(@"C:\Images\test1.jpg");

            var bitmapBytes = GetBitmapBytes(testImage);
            var imgArr = NumSharp.np.array(bitmapBytes);

            var graph = new Graph().as_default();
            graph.Import(modelPath);

            Tensor tensorNum = graph.OperationByName("num_detections").output;
            Tensor tensorBoxes = graph.OperationByName("detection_boxes").output;
            Tensor tensorScores = graph.OperationByName("detection_scores").output;
            Tensor tensorClasses = graph.OperationByName("detection_classes").output;
            Tensor imgTensor = graph.OperationByName("image_tensor").output;

            Tensor[] outTensorArr = new Tensor[] { tensorNum, tensorBoxes, tensorScores, tensorClasses };

            // Start tf session
            using (var sess = tf.Session(graph))
            {
                // Run the op
                var results = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr));

                NDArray[] resultArr = results.Data<NDArray>();

                BuildOutputImage(resultArr);
            }
        }

        public static byte[] GetBitmapBytes(Bitmap image)
        {
            // En garde!
            if (image == null) throw new ArgumentNullException("image");

            BitmapData bmpData = image.LockBits(new Rectangle(0, 0, image.Width, image.Height), ImageLockMode.ReadOnly, image.PixelFormat);
            try
            {
                // Get the address of the first line.
                IntPtr ptr = bmpData.Scan0;

                // Declare an array to hold the bytes of the bitmap.
                int bytes = bmpData.Stride * image.Height;
                byte[] pixelData = new byte[bytes];

                // Copy the RGB values into the array.
                Marshal.Copy(ptr, pixelData, 0, bytes);

                return pixelData;
            }
            finally
            {
                image.UnlockBits(bmpData);
            }
        } 
```

**Comment by Nucs** [comment]
@Oceania2018 In what way does TF.NET accepts an image?

**Comment by mjbedford2017** [comment]
Just a gentle nudge! This is really holding me up. I cannot figure out for the life of me, how to get an in memory bitmap to a 4D array to feed into things like tensorflow.

**Comment by henon** [comment]
@mjbedford2017 check out the [transfer learning example](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.Examples/ImageProcessing/RetrainImageClassifier.cs) in TF.NET, it loads JPEG bitmaps into TF. 
hope it helps.

**Comment by mjbedford2017** [comment]
@henon Thank you for the response. I scanned the whole file (it is massive) just to find the example you are talking about. The only thing that looks remotely close is at line 456:

            // First decode the JPEG image, resize it, and rescale the pixel values.
            var resized_input_values = sess.run(decoded_image_tensor, new FeedItem(image_data_tensor, new Tensor(image_data, TF_DataType.TF_STRING)));

I assume this is what you mean? If so, I am still having an issue with this. I can convert my in memory image to a byte array and use that byte array in place of the "image_data" byte array. However, I would need to figure out the "image_data_tensor" and the "decoded_image_tenor" items along with the session and graph to use. 

Is this the line you meant? If not, can you point me a little closer because I am not seeing it. 

If it is what you meant, can you help me close the gap a bit more? It seems like a huge amount of complicated work just to turn an in memory image into a 4D NDArray to feed into Tensorflow.

Thanks!!!

**Comment by henon** [comment]
also look at line 544 and following in that file. there they directly decode JPG using TF, maybe you can do it the same way?

**Comment by henon** [comment]
also, you don't need to use NDArray at all if that helps. you can directly create a Tensor  from a byte[], or float[] (check out the different constructors of Tensor) and feed that Tensor to the session instead of an NDArray

**Comment by mjbedford2017** [comment]
@henon Thank you again so much for the help, I am really stuck here. I know this is not the place to post Tensorflow.Net items but the original problem is that I cannot feed my image into my tensorflow model for object detection (using a standard MobileNet SSD model) without this error:

> System.Exception: 'input must be 4-dimensional[1] [[{{node Preprocessor/map/while/ResizeImage/ResizeBilinear}}]]'

I noticed in the samples that load the image as a jpeg from a file (which work just fine) they create a 4D NDArray.

I don't care what I use, Tensor or NDArray, but I just need to feed the image in to the tensorflow model, which apparently expects it to be 4D array. The only other challenge is that my images are already in memory, not reading from a file. 

This is where I am stuck.

I will look at line 544 and below to see if that helps me with this problem. 

Thanks again!!!

**Comment by Nucs** [comment]
[Here](https://www.tensorflow.org/api_docs/python/tf/image) are tensorflow's image related function, loading specifically: 

![image](https://user-images.githubusercontent.com/649919/62819986-fbacaf00-bb65-11e9-8748-50c2b5e62890.png)

You should look into them before you use them.

Heres an official guide on how TF handles images: https://www.tensorflow.org/hub/common_signatures/images#image_input

Allow me to quote:

> A signature that takes a batch of images as input accepts them as a dense 4-D tensor of dtype float32 and shape [batch_size, height, width, 3] whose elements are RGB color values of pixels normalized to the range [0, 1]. This is what you get from tf.image.decode_*() followed by tf.image.convert_image_dtype(..., tf.float32).

Based on that quote, it seems that you simply need to read the file's bytes (`File.ReadAllBytes`) and pass them as a 1d to the respective format ` tf.image.decode_*()` where `*` is the format.

@mjbedford2017 Let me know if it helped.

**Comment by henon** [comment]
If you have the images already in memory then you'd use this constructor:
```C#

        /// <summary>
        /// Create a N-dimensional Tensor from the given array
        /// </summary>
        public Tensor(float[] data, long[] shape, TF_DataType? dType = null)  { ...   }

```
Say your images are all in a single `float[]` called `img` where every image is RGB `width` times `height` and there are `batch_size` number of images.

```C#
var tensor = new Tensor(img, new long[]{ batch_size, height, width, 3 });
```

**Comment by mjbedford2017** [comment]
Thank you @Nucs and @henon for the very detailed help and effort on this. First of all, @Nucs, all of those image related functions look really good and I see that they are built into tensorflow. However, in the Tensorflow.Net implementation/wrapper, they are not all implemented. In the tf.Image namespace, there is only the decode_jpeg function. So, this was not going to work. Furthermore, it is a bit complicated to use those functions because you must also have a graph and session to use with them, all of which take time to set up and run. If I want to run this at close to real time, I cannot afford the extra complexity and time. With that said, I am sure your method will work in general if and when Tensorflow.Net implements the other functions.

With that said, @henon, you solution worked great! I did not realize I could create the flat image byte array as a 4D tensor and feed that into Tensorflow.Net but it worked perfectly with this one line of code

var tensor = new Tensor(img, new long[]{ batch_size, height, width, 3 });

Not only did it work by creating me a 4D Tensor but it also fed into Tensorflow.Net with no errors. It is fairly fast, it takes about 75/ms based on my logged stopwatch times, to create the Tensor from the image byte array. This will allow me to run at about 13-14 fps max based on this limitation alone. 

I am going to look at ways to improve this performance a bit but for now, functionally, I am marking this as closed as this solution works great!

Thanks again for all the help to all of you!

**Comment by mjbedford2017** [comment]
Actually, I can't mark it as closed. Feel free to close it.

**Comment by Nucs** [comment]
@mjbedford2017, Glad you found a solution, If I understood @henon's solution correctly,
It can be done similarly in `NumSharp` by calling:
```C#
var _4darray = flatbitmap_ndarray.reshape(batch_size, height, width, 3);
```

**Comment by Nucs** [comment]
@mjbedford2017, I took the liberty to optimize your `NDArray GetBitmapBytes(Bitmap image)`
This should work atleast 50% faster. Note the `//TODO` there which is optional.

```C#
public static NDArray GetBitmapBytes(Bitmap image)
{
    // En garde!
    if (image == null) throw new ArgumentNullException(nameof(image));

    BitmapData bmpData = image.LockBits(new Rectangle(0, 0, image.Width, image.Height), ImageLockMode.ReadOnly, image.PixelFormat);
    try
    {
        unsafe
        {
            //Create a 1d vector without filling it's values to zero (similar to np.empty)
            var nd = new NDArray(NPTypeCode.Byte, Shape.Vector(bmpData.Stride * image.Height), fillZeros: false);

            // Get the respective addresses
            byte* src = (byte*)bmpData.Scan0;
            byte* dst = (byte*)nd.Unsafe.Address; //we can use unsafe because we just allocated that array and we know for sure it is contagious.

            // Copy the RGB values into the array.
            Buffer.MemoryCopy(src, dst, nd.size, nd.size); //faster than Marshal.Copy
            //TODO: replace return with: return nd.reshape(batch_size, height, width, 3);
            return nd;
        }
    }
    finally
    {
        image.UnlockBits(bmpData);
    }
}
```
Let me know the results, I haven't tested it locally

**Comment by mjbedford2017** [comment]
@Nucs Thank you again for the extra effort to help me and others out. I have some findings to report. With your first post, where you took the liberty to re-do the conversion of my in memory image to bytes. There are two major issues. 
1. In the instantiation/creation of the new NDArray, the parameter combination you have provided is not available. First, there is no Shape.Vector. However, I can create a new Shape. Second, there is no option for fillZeros. Also, I cannot specify an NPTypeCode AND the Shape. 
2. In the line `byte* dst = (byte*)nd.Unsafe.Address;` there is no parameter or property for Unsafe in the NDArray (nd). So, this line has an error.

Now for the good news!!!

I followed your other post where I can create a 4D NDArray instead of a Tensor but in a very similar way. This worked great and Tensorflow.Net was able to use this feed input as well. Furthermore, even though the two are similar, it takes 82ms to create a Tensor but only 32ms to create an NDArray with the reshape. This seems to be much faster. Thank you!

For reference, this is the line I ended up using to create a Tensor at 82ms
`var imgArray2 = new Tensor(resized_image.Bytes, new long[] { 1, resized_image.Height, resized_image.Width, 3 });`

And this was to create the NDArray at 32ms
`var imgArr = np.array(resized_image.Bytes).reshape(1, resized_image.Height, resized_image.Width, 3);`

**Comment by Nucs** [comment]
@mjbedford2017, glad to hear.
My bad, these methods are in our [alpha pre-releases](https://www.nuget.org/packages/NumSharp/0.11.0-alpha3) (rewrite of the library) which I forgot that `TF.NET` is yet to support it. This code will be usable once we finish the merging the new alpha work with `TF.NET`.

**Comment by Oceania2018** [comment]
`var imgArr = np.array(resized_image.Bytes).reshape(1, resized_image.Height, resized_image.Width, 3);` only took 32ms ? faster than `new Tensor(resized_image.Bytes, new long[] { 1, resized_image.Height, resized_image.Width, 3 })` ? I can't believe. @mjbedford2017

**Comment by henon** [comment]
@mjbedford2017 are you saying that creating an NDArray + passing into TF is faster than creating a Tensor and passing into TF? I would be surprised if it were.

**Comment by mjbedford2017** [comment]
Sorry for the confusion, let me explain for clarity. First, @henon no, I am not stating anything about TF processing times at the moment. The time I gave was simply to load the in memory Bitmap object into the 4D array to then be later used or passed in to TF. That process alone was 32ms for the NDArray and 82ms for the Tensor. @Oceania2018 unless i am doing it wrong, that is the result i got. I took an in memory Bitmap object and a stopwatch. Created an NPArray, reset stopwatch and then created a Tensor, one right after the other and those are the times I got. Again, just for creating the array, nothing to do with feeding in to TF yet.

**Comment by henon** [comment]
There is still confusion, so I am trying to clear it up. When you create a Tensor the memory is already passed into the native C++ part of TF. When you create an NDArray, that is of course not the case and it still needs to be converted to a Tensor to be able to work with it in TF.

**Comment by itzukah** [comment]
"And this was to create the NDArray at 32ms
var imgArr = np.array(resized_image.Bytes).reshape(1, resized_image.Height, resized_image.Width, 3);
"
May i know the details of resized_image? Is this a variable only or a function?

**Comment by Nucs** [comment]
@itzukah, please take a look at our [wiki](https://github.com/SciSharp/NumSharp/wiki/Bitmap-Extensions) for how to load an image Into `System.Drawing.Bitmap`. After you have it as a `Bitmap` you can resize it and load into a `NDArray` using `bitmap.ToNDArray()` extension.
