### ISSUE TITLE
Implement np.cumsum

### ISSUE THREAD

**Issue by Plankton555** [SciSharp/NumSharp#305]
Return the cumulative sum of the elements along a given axis.

NumPy docs: https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumsum.html

I think the corresponding NumSharp file should be located in https://github.com/SciSharp/NumSharp/tree/master/src/NumSharp.Core/Math

**Comment by Plankton555** [comment]
Basic version implemented in https://github.com/Plankton555/NumSharp/commit/7c081cf0a34d1d091b16c52a1f08208e54a83efb.

**Comment by Oceania2018** [comment]
@Plankton555 Did you PR?

**Comment by Plankton555** [comment]
No, not yet. I should pull that code out to a separate commit and do a PR, but for now it's baked into another feature (np.random.choice).

**Comment by Plankton555** [comment]
Code refactored and submitted as a PR https://github.com/SciSharp/NumSharp/pull/307

**Comment by Plankton555** [comment]
Still just a simple version, I didn't look into support for multidimensional NDArrays.

**Comment by henon** [comment]
I suggest to mark those tests which are failing due to known issues (not implemented, known bug, etc) as ignored with a message like this [Ignore("Summing over axis not implemented yet")]

The advantages are that all tests always pass if everything is ok and we immediately see if we break something.  Also using [Ignored] encourages to add more test cases which would not be added otherwise.

**Comment by Plankton555** [comment]
Sounds fine by me. Do you want to do it or should I?

**Comment by henon** [comment]
I leave it to you guys, just suggesting a good thumb rule

**Comment by Plankton555** [comment]
Fixed and submitted as a pull request https://github.com/SciSharp/NumSharp/pull/308
